### ISSUE TITLE
Most instrument sounds not working

### ISSUE THREAD

**Issue by zlintz14** [erinlyons/comp580project#2]
This is a really cool idea! I like the UI a lot it looks nice and the site is very accessible. I'm not sure if this was just me, but I could not get the Piano, Cello, Guitar, or DJ sounds to work. The only instrument I could get sound from was the Drums. Also, when the reader was reading the instrument options, it never read 'DJ'. Other than that, looks good!

**Comment by gbishop** [comment]
Same here. I see what looks like a timing issue. Log attached.
[erinlyons.github.io-1588702521781.log](https://github.com/erinlyons/comp580project/files/4582868/erinlyons.github.io-1588702521781.log)

Drum works great. I'm impressed with the very small delay after pressing a key. Well done.

But Cello doesn't work at all. No speech, no sounds.

**Comment by erinlyons** [comment]
@gbishop I'm very confused why that is happening since I thought we had fixed this issue. It has worked perfectly well for myself, my teammates, and several other people who I have asked to demo the code. I'm looking into it now and would be open to suggestions for how we can fix this issue.

**Comment by gbishop** [comment]
You've pushed your latest code to github pages?

It looks like a timing issue to me where you are attempting to do something
to a node before it is ready. Don't do anything until you get the onload
signal.

**Comment by tsionc** [comment]
@gbishop  by any chance for the Cello did you press the right or left keys first. If not this is how you will be able to move to the different instruments and when you want to play a sound you hold on to space or you can press enter to hear the notes name.

**Comment by gbishop** [comment]
Why a totally different interface on that page? Choose one and stick with
it.

**Comment by tsionc** [comment]
@gbishop all the other pages besides the drums have the same instructions as the Cello but we will make the update to the drums page and update it soon.  Thank you for the feedback

**Comment by gbishop** [comment]
I prefer the interface on the drum page. Hit a key, hear the instrument.
Nice.

But, they should be consistent, so changing the drum page is likely the
best option at this point.

**Comment by erinlyons** [comment]
@gbishop The reason we did this interface is because there are 12 pitches in the musical scale, but we wanted to stick to a few core keys (arrows, enter, space) rather than using 12 different keys  on the keyboard to improve accessibility for our visually impaired audience. So for the pitched instruments (cello, piano, and guitar) where there are 12 notes we designed it so that using the arrow keys, you can scroll through the notes in the scale in chronological order, then use the space key to play the sound of the pitch you are on or use the enter key to hear the letter name of the note. There is a "How To Play" page that explains these instructions and reads them aloud. 

For the drum kit, there are only 6 sounds that are not in any particular chronological order, so rather than having to scroll using the arrow keys to get to the sound you want, we designed it you could just hit the key assigned to that sound. After your comment about sticking to one interface for all different instrument pages, we changed the Drum page so that it matches the other instrument pages. Press the right arrow to begin scrolling through the sound options, press space to play each sound, press enter to hear the name of the current sound. 

Let us know if this resolves the issue.

**Comment by gbishop** [comment]
I see. The thing I don't like about that decision is it makes it hard
(impossible?) to "jam" with it. You can play notes but not freely.

I think it would be more fun if you could trigger the notes directly.

This is not required. Your project is fine but it would be much better if
players could truly jam.

See what I mean?
